steps:
  - name: maven:3-openjdk-11
    entrypoint: mvn
    args: ['--version']
  - name: maven:3-openjdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-openjdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/trip:$SHORT_SHA", "."]
images: ["gcr.io/$PROJECT_ID/trip:$SHORT_SHA"]